filename = input('파일 이름을 입력:')
removestring = input("제거 할 문자열 입력:")
ifp = open(filename)
s = ifp.read()
newS = s.replace(removestring,'')
ifp.close()
ofp = open(filename,'w')
print(newS,file=ofp,end='')
ofp.close()
print('완료')
